# Generated by Django 4.1.1 on 2023-01-05 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('X', 'Xbox'), ('S', 'Playstation'), ('P', 'PC')], default='X', max_length=1)),
                ('game_genre', models.CharField(choices=[('ADV', 'Adventure'), ('ACT', 'Action'), ('IND', 'Indie'), ('RPG', 'Role Playing Games'), ('SHO', 'Shooting and Combat Games'), ('SIM', 'Simulators'), ('SPO', 'Sports and Racing'), ('STR', 'Strategy and Puzzles')], default='ADV', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], max_length=1)),
                ('bio', models.TextField(blank=True)),
                ('favorite_genre', models.CharField(choices=[('ADV', 'Adventure'), ('ACT', 'Action'), ('IND', 'Indie'), ('RPG', 'Role Playing Games'), ('SHO', 'Shooting and Combat Games'), ('SIM', 'Simulators'), ('SPO', 'Sports and Racing'), ('STR', 'Strategy and Puzzles')], default='ADV', max_length=3)),
                ('contact_info', models.CharField(max_length=250)),
                ('favorite_games', models.ManyToManyField(to='main_app.game')),
                ('likes', models.ManyToManyField(related_name='liked_by', to='main_app.profile')),
                ('matches', models.ManyToManyField(related_name='matched_with', to='main_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('E', 'Everyone')], default='M', max_length=1)),
                ('age_range_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('age_range_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
