# Generated by Django 4.1.1 on 2023-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="interest",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("N", "Non-Binary"),
                    ("E", "Everyone"),
                ],
                default="M",
                max_length=1,
            ),
        ),
    ]
