# Generated by Django 4.1.1 on 2022-12-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_user_profile_user_id_alter_profile_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user",
        ),
    ]
