# Generated by Django 4.1.1 on 2022-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_profile_display_name_alter_profile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="test", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="test", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(max_length=25),
        ),
    ]
