# Generated by Django 4.1.1 on 2022-12-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("W", "Women"), ("O", "Other")], max_length=1
            ),
        ),
    ]
