# Generated by Django 4.1.1 on 2022-12-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_preference_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="gender",
            new_name="interest",
        ),
    ]
