# Generated by Django 4.1.1 on 2022-12-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_rename_gender_preference_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="name",
        ),
        migrations.AddField(
            model_name="game",
            name="game",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="system",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photo",
            name="caption",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_genre",
            field=models.CharField(choices=[], max_length=1),
        ),
        migrations.AlterField(
            model_name="game",
            name="platform",
            field=models.CharField(
                choices=[("C", "Console"), ("P", "PC")], max_length=1
            ),
        ),
    ]
