# Generated by Django 4.1.1 on 2022-12-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0011_remove_game_name_game_game_game_system_photo_caption_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="max_age",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="min_age",
        ),
        migrations.AddField(
            model_name="preference",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("R1", "18-24"),
                    ("R2", "25-34"),
                    ("R3", "35-44"),
                    ("R4", "45-54"),
                    ("R5", "50+"),
                ],
                default="R1",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
