# Generated by Django 4.1.4 on 2022-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_game_name_game_game_game_system_photo_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(choices=[('ADV', 'Adventure'), ('ACT', 'Action'), ('IND', 'Indie'), ('RPG', 'Role Playing Games'), ('SHO', 'Shooting and Combat Games'), ('SIM', 'Simulators'), ('SPO', 'Sports and Racing'), ('STR', 'Strategy and Puzzles')], max_length=3),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interest',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('T', 'Trans'), ('A', 'All')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('N', 'Non-Binary'), ('P', 'Prefer not to say')], max_length=1),
        ),
    ]
