# Generated by Django 4.1.1 on 2022-12-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0012_remove_preference_max_age_remove_preference_min_age_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("R1", "18-24"),
                    ("R2", "25-34"),
                    ("R3", "35-44"),
                    ("R4", "45-54"),
                    ("R5", "55+"),
                ],
                max_length=2,
            ),
        ),
    ]
