# Generated by Django 4.1.4 on 2022-12-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_game_game_genre_alter_preference_interest_and_more'),
        ('main_app', '0012_profile_favorite_genre_alter_game_game_genre_and_more'),
        ('main_app', '0013_alter_preference_age_range'),
    ]

    operations = [
    ]
