# Generated by Django 4.1.1 on 2022-12-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_merge_20221228_2209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorite_genre",
            field=models.CharField(
                choices=[
                    ("ADV", "Adventure"),
                    ("ACT", "Action"),
                    ("IND", "Indie"),
                    ("RPG", "Role Playing Games"),
                    ("SHO", "Shooting and Combat Games"),
                    ("SIM", "Simulators"),
                    ("SPO", "Sports and Racing"),
                    ("STR", "Strategy and Puzzles"),
                ],
                default="ADV",
                max_length=3,
            ),
        ),
    ]
