# Generated by Django 4.1.1 on 2022-12-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_alter_profile_favorite_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="system",
        ),
    ]
