# Generated by Django 4.1.4 on 2022-12-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20221228_2220'),
        ('main_app', '0015_alter_profile_favorite_genre'),
    ]

    operations = [
    ]
