# Generated by Django 4.1.1 on 2022-12-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_remove_game_system"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="game",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="game",
            name="game_genre",
            field=models.CharField(
                choices=[
                    ("ADV", "Adventure"),
                    ("ACT", "Action"),
                    ("IND", "Indie"),
                    ("RPG", "Role Playing Games"),
                    ("SHO", "Shooting and Combat Games"),
                    ("SIM", "Simulators"),
                    ("SPO", "Sports and Racing"),
                    ("STR", "Strategy and Puzzles"),
                ],
                default="ADV",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="platform",
            field=models.CharField(
                choices=[("X", "Xbox"), ("S", "Playstation"), ("P", "PC")],
                default="X",
                max_length=1,
            ),
        ),
    ]
