# Generated by Django 4.1.4 on 2022-12-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20221228_2238'),
        ('main_app', '0017_rename_game_game_name_alter_game_game_genre_and_more'),
    ]

    operations = [
    ]
