# Generated by Django 4.1.4 on 2022-12-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20221230_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(choices=[('ADV', 'Adventure'), ('ACT', 'Action'), ('IND', 'Indie'), ('RPG', 'Role Playing Games'), ('SHO', 'Shooting and Combat Games'), ('SIM', 'Simulators'), ('SPO', 'Sports and Racing'), ('STR', 'Strategy and Puzzles')], default='ADV', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('X', 'Xbox'), ('S', 'Playstation'), ('P', 'PC')], default='X', max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='age_range',
            field=models.CharField(choices=[('R1', '18-24'), ('R2', '25-34'), ('R3', '35-44'), ('R4', '45-54'), ('R5', '55+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interest',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('T', 'Trans'), ('A', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_genre',
            field=models.CharField(choices=[('ADV', 'Adventure'), ('ACT', 'Action'), ('IND', 'Indie'), ('RPG', 'Role Playing Games'), ('SHO', 'Shooting and Combat Games'), ('SIM', 'Simulators'), ('SPO', 'Sports and Racing'), ('STR', 'Strategy and Puzzles')], default='ADV', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('N', 'Non-Binary'), ('P', 'Prefer not to say')], max_length=10),
        ),
    ]
