# Generated by Django 4.1.1 on 2023-01-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20221230_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='main_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(related_name='matched_with', to='main_app.profile'),
        ),
    ]
