# Generated by Django 4.1.4 on 2023-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20221230_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='age_filter_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='interest_filter_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='age_range',
            field=models.CharField(choices=[('R1', '18-24'), ('R2', '25-34'), ('R3', '35-44'), ('R4', '45-54'), ('R5', '55+')], default='R1', max_length=2),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interest',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('T', 'Trans'), ('A', 'All')], default='M', max_length=1),
        ),
    ]
