# Generated by Django 4.1.4 on 2023-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_preference_age_filter_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='age_filter_field',
            field=models.CharField(choices=[('Y', 'Use Filter'), ('N', 'Ignore Filter')], default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interest_filter_field',
            field=models.CharField(choices=[('Y', 'Use Filter'), ('N', 'Ignore Filter')], default='Y', max_length=2),
        ),
    ]
