# Generated by Django 4.1.4 on 2023-01-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_room_alter_game_game_genre_alter_game_platform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
