# Generated by Django 4.1.1 on 2023-01-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_profile_likes_profile_matches"),
        ("main_app", "0021_delete_message_delete_room"),
    ]

    operations = []
